---
all:
  hosts:
    nexus:
      ansible_host: 158.160.73.117
      ansible_user: thegamer8161
      ansible_ssh_private_key_file: "~/ci/05-teamcity/yc-cicd"
  children:
    nexus:
      hosts:
        nexus:
  vars:
    ansible_connection_type:
    ansible_user: thegamer8161